# Generated by Django 4.2.1 on 2023-06-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Катеогория сообщения', 'verbose_name_plural': 'Катеогория сообщений'},
        ),
    ]
