# Generated by Django 4.2.1 on 2023-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postnewstype',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=8),
        ),
    ]
