# Generated by Django 4.2.1 on 2023-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_post_postnewstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postnewstype',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='news', max_length=8),
        ),
    ]
