# Generated by Django 4.2.1 on 2023-06-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
